/**
 * Seed data for Firestore
 * Run this script to populate the database with initial avatars and voices
 */

export const sampleAvatars = [
  {
    id: 'avatar_sarah_001',
    name: 'Sarah',
    previewUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    previewVideoUrl: 'https://storage.googleapis.com/videoai-samples/sarah-preview.mp4',
    tags: ['professional', 'business', 'young'],
    gender: 'female' as const,
    age: 'young_adult' as const,
    experience: 'expert' as const,
    accessories: ['laptop', 'glasses'],
    emotions: ['calm', 'smiling', 'enthusiastic'],
    skinTone: 'light' as const,
    backgroundUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c',
    isPopular: true,
  },
  {
    id: 'avatar_james_002',
    name: 'James',
    previewUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    previewVideoUrl: 'https://storage.googleapis.com/videoai-samples/james-preview.mp4',
    tags: ['casual', 'friendly', 'tech'],
    gender: 'male' as const,
    age: 'adult' as const,
    experience: 'expert' as const,
    accessories: ['phone', 'headphones'],
    emotions: ['excited', 'smiling', 'enthusiastic'],
    skinTone: 'medium' as const,
    backgroundUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    isPopular: true,
  },
  {
    id: 'avatar_maria_003',
    name: 'Maria',
    previewUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    previewVideoUrl: 'https://storage.googleapis.com/videoai-samples/maria-preview.mp4',
    tags: ['professional', 'corporate', 'confident'],
    gender: 'female' as const,
    age: 'adult' as const,
    experience: 'expert' as const,
    accessories: ['jewelry', 'suit'],
    emotions: ['serious', 'calm', 'smiling'],
    skinTone: 'medium_dark' as const,
    backgroundUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
    isPopular: true,
  },
  {
    id: 'avatar_alex_004',
    name: 'Alex',
    previewUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    previewVideoUrl: 'https://storage.googleapis.com/videoai-samples/alex-preview.mp4',
    tags: ['casual', 'creative', 'artist'],
    gender: 'male' as const,
    age: 'young_adult' as const,
    experience: 'intermediate' as const,
    accessories: ['hat', 'scarf'],
    emotions: ['excited', 'enthusiastic', 'smiling'],
    skinTone: 'light' as const,
    backgroundUrl: 'https://images.unsplash.com/photo-1497366672149-e5e4b4d34eb3',
    isPopular: false,
  },
  {
    id: 'avatar_priya_005',
    name: 'Priya',
    previewUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    previewVideoUrl: 'https://storage.googleapis.com/videoai-samples/priya-preview.mp4',
    tags: ['professional', 'tech', 'modern'],
    gender: 'female' as const,
    age: 'young_adult' as const,
    experience: 'expert' as const,
    accessories: ['glasses', 'laptop'],
    emotions: ['calm', 'serious', 'smiling'],
    skinTone: 'medium' as const,
    backgroundUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    isPopular: true,
  },
];

export const sampleVoices = [
  {
    id: 'voice_rachel_001',
    name: 'Rachel',
    previewUrl: 'https://storage.googleapis.com/videoai-samples/rachel-preview.mp3',
    language: 'en',
    accent: 'american',
    age: 'middle_aged' as const,
    gender: 'female' as const,
    provider: 'elevenlabs' as const,
    elevenLabsVoiceId: '21m00Tcm4TlvDq8ikWAM', // Real ElevenLabs voice ID
  },
  {
    id: 'voice_antoni_002',
    name: 'Antoni',
    previewUrl: 'https://storage.googleapis.com/videoai-samples/antoni-preview.mp3',
    language: 'en',
    accent: 'american',
    age: 'young' as const,
    gender: 'male' as const,
    provider: 'elevenlabs' as const,
    elevenLabsVoiceId: 'ErXwobaYiN019PkySvjV',
  },
  {
    id: 'voice_bella_003',
    name: 'Bella',
    previewUrl: 'https://storage.googleapis.com/videoai-samples/bella-preview.mp3',
    language: 'en',
    accent: 'british',
    age: 'young' as const,
    gender: 'female' as const,
    provider: 'elevenlabs' as const,
    elevenLabsVoiceId: 'EXAVITQu4vr4xnSDxMaL',
  },
  {
    id: 'voice_josh_004',
    name: 'Josh',
    previewUrl: 'https://storage.googleapis.com/videoai-samples/josh-preview.mp3',
    language: 'en',
    accent: 'american',
    age: 'young' as const,
    gender: 'male' as const,
    provider: 'elevenlabs' as const,
    elevenLabsVoiceId: 'TxGEqnHWrfWFTfGW9XjX',
  },
  {
    id: 'voice_charlotte_005',
    name: 'Charlotte',
    previewUrl: 'https://storage.googleapis.com/videoai-samples/charlotte-preview.mp3',
    language: 'en',
    accent: 'australian',
    age: 'middle_aged' as const,
    gender: 'female' as const,
    provider: 'elevenlabs' as const,
    elevenLabsVoiceId: 'XB0fDUnXU5powFXDhCwa',
  },
];

export const pricingPlans = [
  {
    id: 'plan_free',
    name: 'free',
    displayName: 'Free',
    price: 0,
    currency: 'usd',
    interval: 'month',
    credits: 5,
    features: [
      '5 free credits',
      'Access to all avatars',
      'Basic voice options',
      'All video formats',
      'Watermarked videos',
    ],
  },
  {
    id: 'plan_starter',
    name: 'starter',
    displayName: 'Starter',
    price: 2900, // $29.00 in cents
    currency: 'usd',
    interval: 'month',
    credits: 50,
    features: [
      '50 credits per month',
      '300+ AI avatars',
      'ElevenLabs voices',
      'No watermark',
      'All formats (9:16, 16:9, 1:1)',
      'Priority support',
    ],
    stripeProductId: 'prod_starter',
    stripePriceId: 'price_starter',
  },
  {
    id: 'plan_creator',
    name: 'creator',
    displayName: 'Creator',
    price: 7900, // $79.00 in cents
    currency: 'usd',
    interval: 'month',
    credits: 150,
    features: [
      '150 credits per month',
      'Everything in Starter',
      'Voice cloning (5 voices)',
      'Custom avatars',
      'Bulk generation',
      'API access',
      'Team collaboration',
      'Priority support',
    ],
    stripeProductId: 'prod_creator',
    stripePriceId: 'price_creator',
  },
  {
    id: 'plan_pro',
    name: 'pro',
    displayName: 'Pro',
    price: 19900, // $199.00 in cents
    currency: 'usd',
    interval: 'month',
    credits: -1, // Unlimited
    features: [
      'Unlimited credits',
      'Everything in Creator',
      'Unlimited voice cloning',
      'Unlimited custom avatars',
      'White-label option',
      'Dedicated account manager',
      'SLA guarantee',
      'Custom integrations',
    ],
    stripeProductId: 'prod_pro',
    stripePriceId: 'price_pro',
  },
];
